root: true
env:
  browser: true
  es2020: true
extends:
  - plugin:prettier/recommended
ignorePatterns:
  - dist
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ['./client/tsconfig.json', './server/tsconfig.json', './client/tsconfig.node.json']
plugins:
  - react
rules:
  no-console: warn
  react/react-in-jsx-scope: off
