pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:albsbz-hom/patterns.git
          - cd patterns.git
          - git push --mirror git@github.com:albsbz/patterns.git